name: Atualizar Gist Diariamente

on:
  schedule:
    - cron: '0 0 * * *' 

jobs:
  update-moodfi-gist-database:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Use a versão desejada do Node.js
      - name: Run TypeScript Script
        run: |
          npm install
          npm start
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
