name: Mood-Fi Live stream Updater

on:
  schedule:
    - cron: '0 0 * * *' 

jobs:
  update-moodfi-gist-database:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2
        
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
      - name: Run TypeScript Script
        run: |
          npm install
          npm run build
          npm start
        env:
          DATABASE_GIST_PERSONAL_TOKEN: ${{ secrets.DATABASE_GIST_PERSONAL_TOKEN }}
          YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
